apiVersion: apps/v1
kind: Deployment
metadata:
  name:  habib
  namespace: demo
spec:
  selector:
    matchLabels:
      app: habib
  template:
    metadata:
      labels:
        app: habib
    spec:
      containers:
        - name: habib
          image: habib4tech/scrum-dhaka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
